# Generated by Django 3.2.4 on 2021-07-09 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurements',
            name='location',
            field=models.CharField(max_length=256),
        ),
    ]
