# Generated by Django 3.2.4 on 2021-06-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caller',
        ),
    ]
