# Generated by Django 3.2.4 on 2021-07-08 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_caller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='estimated_amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='caller',
            name='list_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
