# Generated by Django 3.2.4 on 2021-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210708_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caller',
            name='estimated_amount',
            field=models.IntegerField(default=0),
        ),
    ]
