# Generated by Django 3.2.7 on 2021-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_assistant_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
