# Generated by Django 3.2.7 on 2021-09-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210924_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
