# Generated by Django 3.2.4 on 2021-07-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_alter_caller_estimated_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('caller_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.caller')),
                ('is_connected', models.BooleanField(default=False)),
            ],
            bases=('accounts.caller',),
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
